
import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "readhub",
  description: "Generated by create next app",
  manifest: '/manifest.webmanifest',
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png'
  }
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <>
      {children}
    </>
  );
}
