import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
});

// const roboto = Roboto({
//   variable: "--font-arial",
//   subsets: ["latin"],
// });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        className={`${funnelDisplay.variable} antialiased`}
        suppressHydrationWarning
      >
        <>{children}</>
      </body>
    </html>
  );
}
