import { NextIntlClientProvider } from 'next-intl';
// import type { Metadata } from "next";
import { useLocale } from 'next-intl';
import { ThemeProvider } from "next-themes";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Toaster from '@/components/ui/Toaster';
import { funnelDisplay } from "@/assets/fonts/funnelDisplay";
import { cairo } from "@/assets/fonts/cairo";
import { UserProvider } from "@/context/userContext";
import Head from 'next/head';

// export const metadata: Metadata = {
//   title: "readhub",
//   description: "Generated by create next app",
//   manifest: '/manifest.json',
//   themeColor: '#000000',
//   icons: {
//     icon: '/favicon.svg',
//     shortcut: '/favicon.ico',
//     apple: '/apple-touch-icon.png'
//   }
// };

export default function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = useLocale();

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      dir={locale === "en" ? "ltr" : "rtl"}
      className="dark scheme-light dark:scheme-dark"
    >
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="manifest" href="/manifest.webmanifest" />
        <link rel="icon" href="/favicon-96x96.png" media="(prefers-color-scheme: light)" />
        <link rel="icon" href="/favicon.svg" media="(prefers-color-scheme: dark)" />
      </Head>
      <body
        suppressHydrationWarning
        className={`${funnelDisplay.variable} ${cairo.variable} ${cairo.className} antialiased bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-50`}
      >
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <ReactQueryProvider>
              <UserProvider>
                {children}
                <Toaster />
              </UserProvider>
            </ReactQueryProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
