import { NextIntlClientProvider } from 'next-intl';
import Header from '@/components/Header';
import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import { useLocale } from 'next-intl';
// import "../globals.css";
import { ThemeProvider } from "next-themes";

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "readhub",
  description: "Generated by create next app",
};
export default function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  // Ensure that the incoming `locale` is valid
  const locale = useLocale();

  return (
    <html lang={locale} suppressHydrationWarning dir={locale == 'en' ? 'ltr' : 'rtl'} className="dark scheme-light dark:scheme-dark"
    >
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
      <body suppressHydrationWarning className={`${funnelDisplay.variable} antialiased dark bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-50`}>
        <NextIntlClientProvider>
            <Header />
            <div className='pt-24 container mx-auto px-4'>

              {children}

            </div>
        </NextIntlClientProvider>
      </body>
          </ThemeProvider>
    </html>
  );
}