import { NextIntlClientProvider } from 'next-intl';
import type { Metadata } from "next";
import { useLocale } from 'next-intl';
import { ThemeProvider } from "next-themes";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Toaster  from '@/components/ui/Toaster'; 
import { funnelDisplay } from "@/assets/fonts/funnelDisplay";
import { cairo } from "@/assets/fonts/cairo";

export const metadata: Metadata = {
  title: "readhub",
  description: "Generated by create next app",
};
export default function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const locale = useLocale();

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      dir={locale == "en" ? "ltr" : "rtl"}
      className="dark scheme-light dark:scheme-dark"
    >
      <body
        suppressHydrationWarning
        className={`${funnelDisplay.variable} ${cairo.variable} ${cairo.className} antialiased bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-50`}
      >
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <ReactQueryProvider >
                {children}
              <Toaster />

            </ReactQueryProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
